# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18f012be57268f476a2a3ce48b1e6606e44186218d4a982a1208c1ef3693294e20829965ce08448539f1cd258b90e835c0149d33a283f86fd040fc30bd3e27bc

test:
  secret_key_base: c57ba8b0af9df3909781892de238456270a24acc9ae80bc18d3e6f107d44148feac88073cb88126e02082318c7d1561c09306a0e9334e21dec1747faeeaffc22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
